DROP TABLE IF EXISTS files;
CREATE TABLE files (
  id VARCHAR(36) NOT NULL,
  title VARCHAR(127) NOT NULL,
  filename VARCHAR(127) NOT NULL,
  size INT NOT NULL,
  mimetype VARCHAR(63) NOT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id)
);
